HEROES = {
    "Abaddon": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/26/Abaddon_icon.png",
    "Alchemist": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fe/Alchemist_icon.png",
    "Ancient Apparition": "https://gamepedia.cursecdn.com/dota2_gamepedia/6/67/Ancient_Apparition_icon.png",
    "Anti-Mage": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8e/Anti-Mage_icon.png",
    "Arc Warden": "https://gamepedia.cursecdn.com/dota2_gamepedia/0/07/Arc_Warden_icon.png",
    "Axe": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/23/Axe_icon.png",
    "Bane": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c3/Bane_icon.png",
    "Batrider": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f2/Batrider_icon.png",
    "Beastmaster": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d9/Beastmaster_icon.png",
    "Bloodseeker": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/56/Bloodseeker_icon.png",
    "Bounty Hunter": "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a6/Bounty_Hunter_icon.png",
    "Brewmaster": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1e/Brewmaster_icon.png",
    "Bristleback": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4d/Bristleback_icon.png",
    "Broodmother": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/df/Broodmother_icon.png",
    "Centaur Warrunner": "https://gamepedia.cursecdn.com/dota2_gamepedia/e/ed/Centaur_Warrunner_icon.png",
    "Chaos Knight": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fe/Chaos_Knight_icon.png",
    "Chen": "https://gamepedia.cursecdn.com/dota2_gamepedia/6/61/Chen_icon.png",
    "Clinkz": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/cb/Clinkz_icon.png",
    "Clockwerk": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d8/Clockwerk_icon.png",
    "Crystal Maiden": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/27/Crystal_Maiden_icon.png",
    "Dark Seer": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c5/Dark_Seer_icon.png",
    "Dark Willow": "https://gamepedia.cursecdn.com/dota2_gamepedia/3/3c/Dark_Willow_icon.png",
    "Dazzle": "https://gamepedia.cursecdn.com/dota2_gamepedia/e/e6/Dazzle_icon.png",
    "Death Prophet": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d7/Death_Prophet_icon.png",
    "Disruptor": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/97/Disruptor_icon.png",
    "Doom": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/40/Doom_icon.png",
    "Dragon Knight": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/59/Dragon_Knight_icon.png",
    "Drow Ranger": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/80/Drow_Ranger_icon.png",
    "Earth Spirit": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/be/Earth_Spirit_icon.png",
    "Earthshaker": "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a5/Earthshaker_icon.png",
    "Elder Titan": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1a/Elder_Titan_icon.png",
    "Ember Spirit": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/91/Ember_Spirit_icon.png",
    "Enchantress": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/41/Enchantress_icon.png",
    "Enigma": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f7/Enigma_icon.png",
    "Faceless Void": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/73/Faceless_Void_icon.png",
    "Grimstroke": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d7/Grimstroke_icon.png",
    "Gyrocopter": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4f/Gyrocopter_icon.png",
    "Huskar": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d3/Huskar_icon.png",
    "Invoker": "https://gamepedia.cursecdn.com/dota2_gamepedia/0/00/Invoker_icon.png",
    "Io": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8d/Io_icon.png",
    "Jakiro": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/2f/Jakiro_icon.png",
    "Juggernaut": "https://gamepedia.cursecdn.com/dota2_gamepedia/0/03/Juggernaut_icon.png",
    "Keeper of the Light": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/b9/Keeper_of_the_Light_icon.png",
    "Kunkka": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c0/Kunkka_icon.png",
    "Legion Commander": "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a2/Legion_Commander_icon.png",
    "Leshrac": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/26/Leshrac_icon.png",
    "Lich": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/bb/Lich_icon.png",
    "Lifestealer": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/2b/Lifestealer_icon.png",
    "Lina": "https://gamepedia.cursecdn.com/dota2_gamepedia/3/35/Lina_icon.png" ,
    "Lion": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/b8/Lion_icon.png",
    "Lone Druid": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/5d/Lone_Druid_icon.png",
    "Luna": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7d/Luna_icon.png",
    "Lycan": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d6/Lycan_icon.png",
    "Magnus": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/ba/Magnus_icon.png",
    "Mars": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9d/Mars_icon.png",
    "Medusa": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/cc/Medusa_icon.png",
    "Meepo": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/85/Meepo_icon.png",
    "Mirana": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/12/Mirana_icon.png",
    # "Monkey King",
    # "Morphling",
    # "Naga Siren",
    # "Nature's Prophet",
    # "Necrophos",
    # "Night Stalker",
    # "Nyx Assassin",
    # "Ogre Magi",
    # "Omniknight",
    # "Oracle",
    # "Outworld Devourer",
    # "Pangolier",
    # "Phantom Assassin",
    # "Phantom Lancer",
    # "Phoenix",
    # "Puck",
    # "Pudge",
    # "Pugna",
    # "Queen of Pain",
    # "Razor",
    # "Riki",
    # "Rubick",
    # "Sand King",
    # "Shadow Demon",
    # "Shadow Fiend",
    # "Shadow Shaman",
    # "Silencer",
    # "Skywrath Mage",
    # "Slardar",
    # "Slark",
    # "Sniper",
    # "Spectre",
    # "Spirit Breaker",
    # "Storm Spirit",
    # "Sven",
    # "Techies",
    # "Templar Assassin",
    # "Terrorblade",
    # "Tidehunter",
    # "Timbersaw",
    # "Tinker",
    # "Tiny",
    # "Treant Protector",
    # "Troll Warlord",
    # "Tusk",
    # "Underlord",
    # "Undying",
    # "Ursa",
    # "Vengeful Spirit",
    # "Venomancer",
    # "Viper",
    # "Visage",
    # "Warlock",
    # "Weaver",
    # "Windranger",
    # "Winter Wyvern",
    # "Witch Doctor",
    # "Wraith King",
    # "Zeus" :
}
