HEROES = {
    "Abaddon": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/26/Abaddon_icon.png",
    "Alchemist": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fe/Alchemist_icon.png",
    "Ancient Apparition": "https://gamepedia.cursecdn.com/dota2_gamepedia/6/67/Ancient_Apparition_icon.png",
    "Anti-Mage": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8e/Anti-Mage_icon.png",
    "Arc Warden": "https://gamepedia.cursecdn.com/dota2_gamepedia/0/07/Arc_Warden_icon.png",
    "Axe": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/23/Axe_icon.png",
    "Bane": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c3/Bane_icon.png",
    "Batrider": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f2/Batrider_icon.png",
    "Beastmaster": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d9/Beastmaster_icon.png",
    "Bloodseeker": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/56/Bloodseeker_icon.png",
    "Bounty Hunter": "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a6/Bounty_Hunter_icon.png",
    "Brewmaster": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1e/Brewmaster_icon.png",
    "Bristleback": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4d/Bristleback_icon.png",
    "Broodmother": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/df/Broodmother_icon.png",
    "Centaur Warrunner": "https://gamepedia.cursecdn.com/dota2_gamepedia/e/ed/Centaur_Warrunner_icon.png",
    "Chaos Knight": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fe/Chaos_Knight_icon.png",
    "Chen": "https://gamepedia.cursecdn.com/dota2_gamepedia/6/61/Chen_icon.png",
    "Clinkz": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/cb/Clinkz_icon.png",
    "Clockwerk": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d8/Clockwerk_icon.png",
    "Crystal Maiden": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/27/Crystal_Maiden_icon.png",
    "Dark Seer": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c5/Dark_Seer_icon.png",
    "Dark Willow": "https://gamepedia.cursecdn.com/dota2_gamepedia/3/3c/Dark_Willow_icon.png",
    "Dazzle": "https://gamepedia.cursecdn.com/dota2_gamepedia/e/e6/Dazzle_icon.png",
    "Death Prophet": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d7/Death_Prophet_icon.png",
    "Disruptor": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/97/Disruptor_icon.png",
    "Doom": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/40/Doom_icon.png",
    "Dragon Knight": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/59/Dragon_Knight_icon.png",
    "Drow Ranger": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/80/Drow_Ranger_icon.png",
    "Earth Spirit": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/be/Earth_Spirit_icon.png",
    "Earthshaker": "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a5/Earthshaker_icon.png",
    "Elder Titan": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1a/Elder_Titan_icon.png",
    "Ember Spirit": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/91/Ember_Spirit_icon.png",
    "Enchantress": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/41/Enchantress_icon.png",
    "Enigma": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f7/Enigma_icon.png",
    "Faceless Void": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/73/Faceless_Void_icon.png",
    "Grimstroke": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d7/Grimstroke_icon.png",
    "Gyrocopter": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4f/Gyrocopter_icon.png",
    "Huskar": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d3/Huskar_icon.png",
    "Invoker": "https://gamepedia.cursecdn.com/dota2_gamepedia/0/00/Invoker_icon.png",
    "Io": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8d/Io_icon.png",
    "Jakiro": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/2f/Jakiro_icon.png",
    "Juggernaut": "https://gamepedia.cursecdn.com/dota2_gamepedia/0/03/Juggernaut_icon.png",
    "Keeper of the Light": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/b9/Keeper_of_the_Light_icon.png",
    "Kunkka": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c0/Kunkka_icon.png",
    "Legion Commander": "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a2/Legion_Commander_icon.png",
    "Leshrac": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/26/Leshrac_icon.png",
    "Lich": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/bb/Lich_icon.png",
    "Lifestealer": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/2b/Lifestealer_icon.png",
    "Lina": "https://gamepedia.cursecdn.com/dota2_gamepedia/3/35/Lina_icon.png" ,
    "Lion": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/b8/Lion_icon.png",
    "Lone Druid": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/5d/Lone_Druid_icon.png",
    "Luna": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7d/Luna_icon.png",
    "Lycan": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d6/Lycan_icon.png",
    "Magnus": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/ba/Magnus_icon.png",
    "Mars": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9d/Mars_icon.png",
    "Medusa": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/cc/Medusa_icon.png",
    "Meepo": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/85/Meepo_icon.png",
    "Mirana": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/12/Mirana_icon.png",
    "Monkey King": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7b/Monkey_King_icon.png",
    "Morphling": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7b/Morphling_icon.png",
    "Naga Siren": "https://gamepedia.cursecdn.com/dota2_gamepedia/6/60/Naga_Siren_icon.png",
    "Nature's Prophet": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c4/Nature%27s_Prophet_icon.png",
    "Necrophos": "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a6/Necrophos_icon.png",
    "Night Stalker": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/15/Night_Stalker_icon.png",
    "Nyx Assassin": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fa/Nyx_Assassin_icon.png",
    "Ogre Magi": "https://gamepedia.cursecdn.com/dota2_gamepedia/e/e0/Ogre_Magi_icon.png",
    "Omniknight": "https://gamepedia.cursecdn.com/dota2_gamepedia/e/e2/Omniknight_icon.png",
    "Oracle": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/72/Oracle_icon.png",
    "Outworld Devourer": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/99/Outworld_Devourer_icon.png",
    "Pangolier": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4e/Pangolier_icon.png",
    "Phantom Assassin": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8e/Phantom_Assassin_icon.png",
    "Phantom Lancer": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/81/Phantom_Lancer_icon.png",
    "Phoenix": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/14/Phoenix_icon.png",
    "Puck": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/13/Puck_icon.png",
    "Pudge": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c0/Pudge_icon.png",
    "Pugna": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/c0/Pudge_icon.png",
    "Queen of Pain": "https://gamepedia.cursecdn.com/dota2_gamepedia/a/a1/Queen_of_Pain_icon.png",
    "Razor": "https://gamepedia.cursecdn.com/dota2_gamepedia/6/66/Razor_icon.png",
    "Riki": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7d/Riki_icon.png",
    "Rubick": "https://gamepedia.cursecdn.com/dota2_gamepedia/8/8a/Rubick_icon.png",
    "Sand King": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/79/Sand_King_icon.png",
    "Shadow Demon": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f3/Shadow_Demon_icon.png",
    "Shadow Fiend": "https://gamepedia.cursecdn.com/dota2_gamepedia/3/36/Shadow_Fiend_icon.png",
    "Shadow Shaman": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/96/Shadow_Shaman_icon.png",
    "Silencer": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9f/Silencer_icon.png",
    "Skywrath Mage": "https://gamepedia.cursecdn.com/dota2_gamepedia/b/bf/Skywrath_Mage_icon.png",
    "Slardar": "https://gamepedia.cursecdn.com/dota2_gamepedia/7/7e/Slardar_icon.png",
    "Slark": "https://gamepedia.cursecdn.com/dota2_gamepedia/a/aa/Slark_icon.png",
    "Sniper": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/51/Sniper_icon.png",
    "Spectre": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/ff/Spectre_icon.png",
    "Spirit Breaker": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/df/Spirit_Breaker_icon.png",
    "Storm Spirit": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/13/Storm_Spirit_icon.png",
    "Sven": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1b/Sven_icon.png",
    "Techies": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/fa/Techies_icon.png",
    "Templar Assassin": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9c/Templar_Assassin_icon.png",
    "Terrorblade": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/52/Terrorblade_icon.png",
    "Tidehunter": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d5/Tidehunter_icon.png",
    "Timbersaw": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9a/Timbersaw_icon.png",
    "Tinker": "https://gamepedia.cursecdn.com/dota2_gamepedia/d/d1/Tinker_icon.png",
    "Tiny": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/55/Tiny_icon.png",
    "Treant Protector": "https://gamepedia.cursecdn.com/dota2_gamepedia/3/3f/Treant_Protector_icon.png",
    "Troll Warlord": "https://gamepedia.cursecdn.com/dota2_gamepedia/f/f0/Troll_Warlord_icon.png",
    "Tusk": "https://gamepedia.cursecdn.com/dota2_gamepedia/c/ce/Tusk_icon.png",
    "Underlord": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/18/Underlord_icon.png",
    "Undying": "https://gamepedia.cursecdn.com/dota2_gamepedia/6/61/Undying_icon.png",
    "Ursa": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/40/Ursa_icon.png",
    "Vengeful Spirit": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/20/Vengeful_Spirit_icon.png",
    "Venomancer": "https://gamepedia.cursecdn.com/dota2_gamepedia/2/25/Venomancer_icon.png",
    "Viper": "https://gamepedia.cursecdn.com/dota2_gamepedia/5/5f/Viper_icon.png",
    "Visage": "https://gamepedia.cursecdn.com/dota2_gamepedia/9/9e/Visage_icon.png",
    "Warlock": "https://gamepedia.cursecdn.com/dota2_gamepedia/3/3f/Warlock_icon.png",
    "Weaver": "https://gamepedia.cursecdn.com/dota2_gamepedia/0/09/Weaver_icon.png",
    "Windranger": "https://gamepedia.cursecdn.com/dota2_gamepedia/6/60/Windranger_icon.png",
    "Winter Wyvern": "https://gamepedia.cursecdn.com/dota2_gamepedia/4/4a/Winter_Wyvern_icon.png",
    "Witch Doctor": "https://gamepedia.cursecdn.com/dota2_gamepedia/3/33/Witch_Doctor_icon.png",
    "Wraith King": "https://gamepedia.cursecdn.com/dota2_gamepedia/1/1e/Wraith_King_icon.png",
    "Zeus": "https://gamepedia.cursecdn.com/dota2_gamepedia/3/3f/Zeus_icon.png"
}

